# Generated by Django 3.0.7 on 2020-12-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=30)),
                ('CNIC', models.IntegerField(unique=True)),
                ('Relative_Name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Mobile', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
