# Generated by Django 3.0.7 on 2020-12-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('Doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=30)),
                ('Mobile', models.IntegerField()),
                ('OPT_Time', models.CharField(max_length=30)),
                ('OPD_Days', models.CharField(max_length=30)),
                ('Specialization', models.CharField(max_length=30)),
            ],
        ),
    ]
