# Generated by Django 3.0.7 on 2020-12-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.DoctorModel')),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PatientModel')),
            ],
        ),
    ]
