# Generated by Django 3.0.7 on 2020-12-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeModel',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.DateTimeField()),
                ('Discarged_By', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.DoctorModel')),
                ('Disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.testModel')),
                ('Patient_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PatientModel')),
            ],
        ),
    ]
